# Generated by Django 2.0.3 on 2018-04-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzair', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('videolength', models.PositiveIntegerField()),
                ('sharecount', models.PositiveIntegerField()),
                ('commentcount', models.PositiveIntegerField()),
                ('reactioncount', models.PositiveIntegerField()),
                ('post_type', models.CharField(choices=[('status', 's'), ('video', 'v')], max_length=100)),
                ('from_name', models.CharField(blank=True, max_length=200)),
                ('post_hidden', models.BooleanField(choices=[('True', 'T'), ('False', 'F')], max_length=200)),
                ('post_pub', models.BooleanField(choices=[('True', 'T'), ('False', 'F')], max_length=200)),
                ('link_name', models.CharField(blank=True, max_length=200)),
                ('link_cap', models.CharField(blank=True, max_length=200)),
                ('link_desc', models.TextField(blank=True, max_length=200)),
                ('link_url', models.URLField(blank=True)),
                ('media_id', models.PositiveIntegerField(blank=True)),
                ('parent_id', models.PositiveIntegerField(blank=True)),
                ('media_thumbnail', models.URLField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('story_text', models.TextField(blank=True)),
                ('page_id', models.PositiveIntegerField(blank=True)),
                ('created_time', models.TimeField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
