# Generated by Django 2.0.3 on 2018-04-02 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uzair.models
import uzair.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uzair', '0002_auto_20180401_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=uzair.models.upload_csv_file, validators=[uzair.validators.csv_file_validator])),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
